version: "3"
services:
  paperlens:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 4000:4000
    container_name: paperlens
    working_dir: /home/circleci/project/repo
    volumes:
      - /home/circleci/project:/home/circleci/project
    tty: false
    environment:
      POSTGRES_TESTING_HOST: postgres
  postgres:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperlens_dev
