# Elixir CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-elixir/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    environment:
      POSTGRES_TESTING_HOST: postgres
    docker:
      - image: "cimg/base:current"
    parallelism: 1
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run:
          name: Create the containers
          command: docker-compose up --no-start --build postgres paperlens
      - run:
          name: Start the containers
          command: docker-compose up -d postgres
      - run: # may delete this step I think
          name: Copy code onto elixir docker image
          command: |
            docker cp /home/circleci/repo paperlens:/home/circleci/project
      - run:
          name: Install deps
          command: |
            docker-compose run --rm paperlens "mix deps.get"
      - run:
          name: Create testing database
          command: |
            docker-compose run --rm paperlens "MIX_ENV=test mix ecto.create"
      - run:
          name: Run tests
          command: |
            docker-compose run --rm paperlens "mix test"
      - run:
          name: Generate a release file
          command: |
            docker-compose run --rm paperlens "export DATABASE_URL=ecto://postgres:postgres@$POSTGRES_TESTING_HOST/phoenix_react_dev \
                && mix deps.get --only prod \
                && MIX_ENV=prod mix compile \
                && mix webapp \
                && cd apps/paperlens_web ; mix phx.gen.release \
                && MIX_ENV=prod mix release"
