# Elixir CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-elixir/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    environment:
      POSTGRES_TESTING_HOST: postgres
    docker:
      - image: "cimg/base:current"
    parallelism: 1
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run:
          name: Create the containers
          command: docker-compose up --no-start --build postgres paperlens
      - run:
          name: Start the containers
          command: docker-compose up -d postgres
      - run: # may delete this step I think
          name: Copy code onto elixir docker image
          command: |
            docker cp /home/circleci/repo paperlens:/home/circleci/project
      - run:
          name: Install deps and run tests
          command: |
            docker-compose run --rm paperlens sh -c "\
              mix local.hex --force \
              && mix local.rebar --force \
              && mix deps.get \
              && MIX_ENV=test mix ecto.create \
              && mix test"
